### ISSUE TITLE
Install docker CS engine

### ISSUE THREAD

**Issue by mapuri** [contiv/ansible#103]
We need to install and validate the CS version of Docker Engine as described here:

https://docs.docker.com/docker-trusted-registry/install/install-csengine/

**Comment by jainvipin** [comment]
@mapuri - in cases we may have to try the standard docker version... should we control this via a variable or some environment? All standard tryouts based on demo_installer would use off the shelf docker engine.

**Comment by mapuri** [comment]
yes sure, we can control it through variable. Do you see this being deployment specific? I think CS engine is free too just that it might not be released as fast as Docker Engine.

Also we need to think what should be the default for us that we test and regress in our environments? I am just wondering if we would be adding a lot more combinations by having both engines.

**Comment by jainvipin** [comment]
@mapuri - I think cluster repo should use CS engine; others standard i.e. default is get.docker.com

**Comment by mapuri** [comment]
closing this issue as per @rkharya 's findings in https://github.com/contiv/cluster/issues/80#issuecomment-206343646 docker-cs version is simply installed by setting `docker_version` variable.
