### ISSUE TITLE
Need to address apt-get update failure

### ISSUE THREAD

**Issue by jojimt** [contiv/ansible#107]
apt-get update errors out on some hosts. The workaround to fix this is to clean up /var/lib/apt/lists.
We need to incorporate this into the ansible scripts to perform this clean up based on the error.

**Comment by mapuri** [comment]
closing this as Ubuntu support is not there and also it is not clear to me if this shall be handled inside or outside the ansible.

Let's track similar issues once we bring back Ubuntu support
