### ISSUE TITLE
etcd out of sync on hosts

### ISSUE THREAD

**Issue by karamsivia** [contiv/ansible#119]
Setup - Non vagrant setup on 2 hosts using net_demo_installer script. Etcd config is out of sync on  hosts when I use control interface eth1 on host1 and control interface eth2 on host 2. etcd is unable to communicate.  To reproduce issue, use config  below
CONNECTION_INFO:
  <server1-ip-or-dns>:
    control: eth1
    data: eth2
  <server2-ip-or-dns>:
    control: eth2
    data: eth1

**Comment by karamsivia** [comment]
CONNECTION_INFO:
192.168.2.10:
control: eth1
data: eth2
192.168.2.11:
control: eth2
data: eth1

**Comment by mapuri** [comment]
@karamsivia 

thanks for reporting the issue.

Just to understand the issue of `Etcd config is out of sync on hosts` a bit more, is the etcd service failing to start or is etcd cluster not getting formed ?

Can you share the following info:
- output of `sudo systemctl status -ln100 etcd` from both the hosts
- OS version of these hosts
- And for the steps to reproduce, does this happens on the first run of the net-demo-installer itself? Or was there a cleanup also involved (i.e. using a `-r` option of installer)

**Comment by karamsivia** [comment]
I am using ubuntu 15.04.  When I use eth1 as control interface on VM1 , and eth2 as as control interface on VM2 , and use net_demo_installer then etcd.sh is generated under /usr/bin. 

 ETCD_INITIAL_CLUSTER section in etcd.sh on VM1 - gets IPs of eth1 of both VMS,
But
ETCD_INITIAL_CLUSTER section in etcd.sh on VM2 - gets IPs of eth2 of both VMS

and that was causing issue where etcd weren't able to communicate. I don't have setup available currently to provide logs. Issue persists with -r option of installer. Abinandan Prativadi did look at this issue on my VMs.

**Comment by mapuri** [comment]
@karamsivia thanks for sharing the details. I think I understand the issue more now. It appears that the etcd service template picks up the interface name from the host ansible is running one when it should have picked it up from the facts of the other host. I will work on a fix. Thanks.
