### ISSUE TITLE
prune the `base` packages to minimally needed set and move the rest to `dev` or other roles

### ISSUE THREAD

**Issue by mapuri** [contiv/ansible#122]
the base package installs multiple dev packages like git, gcc, perl etc which shouldn't be installed in production environment unless they are needed for running or installing the service itself

Following is the list in `base` role that we can most likely move to `dev` role:
    - ntp
    - vim
    - curl
    - git
    - mercurial
    - gcc
    - perl

**Comment by jainvipin** [comment]
@mapuri - were these added for dev environment, and we may share the same base role?

**Comment by mapuri** [comment]
I have no idea, they have there since day zero iirc :)

**Comment by mapuri** [comment]
I thought having this issue open will at least help us track what we need to improve to make ansible production ready
