### ISSUE TITLE
Node status is 'Allocated' though it remains isolated from cluster

### ISSUE THREAD

**Issue by rkharya** [contiv/ansible#135]
9 node scale cluster. One node status allocated but fails to join cluster -

},
    "contiv-aci-scale-6-FCH1924V2F6": {
        "name": "contiv-aci-scale-6-FCH1924V2F6",
        "status": "Allocated",
        "prev-status": "Incomplete",
        "state": "Discovered",
        "prev-state": "Unknown"
    },

[admin@contiv-aci-scale-6 ~]$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

[admin@contiv-aci-scale-6 ~]$ sudo systemctl status -l -n 50 ucp
● ucp.service - Ucp
   Loaded: loaded (/etc/systemd/system/ucp.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-03-22 10:21:11 PDT; 3h 52min ago
 Main PID: 25189 (code=exited, status=1/FAILURE)

Mar 22 10:21:08 contiv-aci-scale-6.cisco.com systemd[1]: Started Ucp.
Mar 22 10:21:08 contiv-aci-scale-6.cisco.com systemd[1]: Starting Ucp...
Mar 22 10:21:08 contiv-aci-scale-6.cisco.com ucp.sh[25189]: starting ucp on contiv-aci-scale-6-FCH1924V2F6[10.193.231.62]
Mar 22 10:21:08 contiv-aci-scale-6.cisco.com ucp.sh[25189]: INFO[0000] All required images are present
Mar 22 10:21:09 contiv-aci-scale-6.cisco.com ucp.sh[25189]: INFO[0000] This engine will join UCP and advertise itself with host address 10.193.231.62 - If this is incorrect, please specify an alternative address with the '--host-address' flag
Mar 22 10:21:09 contiv-aci-scale-6.cisco.com ucp.sh[25189]: INFO[0000] Verifying your system is compatible with UCP
Mar 22 10:21:10 contiv-aci-scale-6.cisco.com ucp.sh[25189]: ERRO[0001] Server response: the system is unlicensed
Mar 22 10:21:10 contiv-aci-scale-6.cisco.com ucp.sh[25189]: FATA[0001] Failed to add host to UCP: the system is unlicensed
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com systemd[1]: ucp.service: main process exited, code=exited, status=1/FAILURE
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: docker: "stop" requires a minimum of 1 argument.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: See 'docker stop --help'.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: Usage:        docker stop [OPTIONS] CONTAINER [CONTAINER...]
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: Stop a running container.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: Sending SIGTERM and then SIGKILL after a grace period
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: docker: "rm" requires a minimum of 1 argument.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: See 'docker rm --help'.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: Usage:        docker rm [OPTIONS] CONTAINER [CONTAINER...]
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com ucp.sh[25412]: Remove one or more containers
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com systemd[1]: ucp.service: control process exited, code=exited status=123
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com systemd[1]: Unit ucp.service entered failed state.
Mar 22 10:21:11 contiv-aci-scale-6.cisco.com systemd[1]: ucp.service failed.

When try to de-commission this node, it aborts with below message -

[admin@contiv-aci-scale-1 ~]$ clusterctl node decommission contiv-aci-scale-6-FCH1924V2F6
FATA[0000] Request: decommission/node/contiv-aci-scale-6-FCH1924V2F6 Response status: "500 Internal Server Error". Response body: "contiv-aci-scale-6-FCH1924V2F6" is a master node and it can only be decommissioned after all worker nodes have been decommissioned

This node was never tried to commissioned as first node - it was not expected to run a master-node.

**Comment by rkharya** [comment]
Restarting UCP services fixed the issue. We may want to debug, so as to why it went into failed state.

**Comment by mapuri** [comment]
@rkharya 

thanks for sharing ansible logs, that helped. The service had failed due to ucp license issue `Failed to add host to UCP: the system is unlicensed`

But I think you mentioned that UCP service shows up as running, is that still the case? From logs it looks like service has exited. If not I think we can close this issue.

> When try to de-commission this node, it aborts with below message -
> [admin@contiv-aci-scale-1 ~]$ clusterctl node decommission contiv-aci-scale-6-FCH1924V2F6
> FATA[0000] Request: decommission/node/contiv-aci-scale-6-FCH1924V2F6 Response status: "500 Internal Server Error". Response body: "contiv-aci-scale-6-FCH1924V2F6" is a master node and it can only be decommissioned after all worker nodes have been decommissioned
> This node was never tried to commissioned as first node - it was not expected to run a master-node.

I think for better tracking this behavior needs to be tracked in cluster repo. Can you also list the steps to reproduce this behavior when you file the issue in cluster repo? Thanks.

**Comment by rkharya** [comment]
Yes, closing the issue. I could have missed re-starting UCP on this node, after taking care of license.
