### ISSUE TITLE
ansible does not upgrade netplugin to the specified version

### ISSUE THREAD

**Issue by jojimt** [contiv/ansible#141]
If a version of netplugin is already installed and we try to upgrade by setting `contiv_network_version` variable, the new version does not get installed.

**Comment by mapuri** [comment]
@jojimt I just tried this out and seems to work.

Note that to upgrade a service we need to run cleanup first (i.e. `-r` flag in case of net_demo_installer). Can you reconfirm the steps to reproduce?

**Comment by jojimt** [comment]
We faced this issue on an SE's setup yesterday. Set contiv_network_version to v0.1-03-16-2016.13-43-59.UTC and ran net_demo_installer -ar. After the install completed, netmaster version showed v0.1-02-27-2016.09-27-46.UTC.

**Comment by mapuri** [comment]
hmm, may be the variable wasn't passed correctly to ansible.

Do you happen to have the changes made to installer to pass the version-variable?

**Comment by jojimt** [comment]
It was done over webex, so i don't have the diffs. We changed the default directly in ansible. If you tried it and it correctly upgrades from version a to version b, let's leave it at that for now.

**Comment by mapuri** [comment]
ok, closing this for now as it doesn't look like ansible issue
