### ISSUE TITLE
ansible does not start ntpd

### ISSUE THREAD

**Issue by jojimt** [contiv/ansible#142]
Even though ansible installs ntp, it does not correctly start the service. This causes time to be out of sync and leads to issues with etcd. We need to make sure we start the service from ansible.

**Comment by mapuri** [comment]
very interesting, why would a distributed service like etcd depend on system time? It is bound to break, not saying we should not fix ntp though.

Just curious, is this etcd behavior documented? I would like to understand it a bit more.
