### ISSUE TITLE
BM control node cluster manager install ansible task failures - install/upgrade base packages (redhat)

### ISSUE THREAD

**Issue by rkharya** [contiv/ansible#175]
Using RHEL 7.\* stock OS on B-series for Contiv Cluster Manager. Installation failed on 'install/upgrade base packages (redhat)' task with below error -

TASK [base : install/upgrade base packages (redhat)] ***************************
Friday 22 April 2016  14:43:29 +0530 (0:00:05.772)       0:00:06.425 **********
failed: [Docker-1] => (item=[u'ntp', u'unzip', u'bzip2', u'curl', u'librbd1-devel', u'python-requests', u'bash-completion', u'kernel', u'libselinux-python']) => {"changed": false, "failed": true, "item": ["ntp", "unzip", "bzip2", "curl", "librbd1-devel", "python-requests", "bash-completion", "kernel", "libselinux-python"], "**msg": "No Package matching 'librbd1-devel' found available**,*\* installed or updated", "rc": 0, "results": ["All packages providing ntp are up to date", "All packages providing unzip are up to date", "All packages providing bzip2 are up to date", "All packages providing curl are up to date"]}
    to retry, use: --limit @./site.retry

PLAY RECAP *********************************************************************
Docker-1                   : ok=3    changed=0    unreachable=0    failed=1
# Friday 22 April 2016  14:43:43 +0530 (0:00:14.080)       0:00:20.506 **********

TASK: base : install/upgrade base packages (redhat) -------------------- 14.08s
TASK: base : install epel release package (redhat) ---------------------- 5.77s
TASK: setup ------------------------------------------------------------- 0.50s
TASK: base : include ---------------------------------------------------- 0.05s
TASK: base : include ---------------------------------------------------- 0.03s

So far we have been using CentOS 7.\* and did not found this issue cropping up so far. We will take care of dependancies manually, this issue is for tracking.

**Comment by rkharya** [comment]
Adding rhel-7-server-rhceph-1.3-osd-rpms repo for rbd library and installing it manually resolved the issue. We need to address this through ansible.

**Comment by erikh** [comment]
That lib is no longer required, just remove it.
