### ISSUE TITLE
Node commissioning failing with ucp-fingerprint file waiting timeout

### ISSUE THREAD

**Issue by rkharya** [contiv/ansible#189]
UCP - 1.1.0
Docker - 1.11.0
Ansible/Cluster - Latest, clonned on 05/09

First node commissioning failing with below error -

May 10 12:42:02 Docker-1.cisco.com clusterm[15446]: level=info msg="failed: [Docker-2-FLM19379EUC](item=ucp-fingerprint) => {\"elapsed\": 300, \"failed\": true, \"item\": \"ucp-fingerprint\", \"msg\": \"Timeout when waiting for file /tmp/ucp-fingerprint\"}"

On master node(Docker-2-FLM19379EUC) /tmp does have docker_license file but does NOT have ucp-fingerprint file -

[cluster-admin@Docker-2 ~]$ ls -ltr /tmp/
total 18024
-rw-------. 1 root root       0 May  6 13:13 yum.log
-rwx------. 1 root root     813 May  6 13:35 ks-script-43mOzu
-rw-r--r--. 1 root root       0 May  6 14:35 storage.log
-rw-r--r--. 1 root root       0 May  6 14:35 program.log
-rw-r--r--. 1 root root       0 May  6 14:35 anaconda.log
-rw-r--r--. 1 root root       0 May  6 14:35 packaging.log
-rw-r--r--. 1 root root       0 May  6 14:35 ifcfg.log
drwxr-xr-x. 2 root root      18 May  6 18:14 hsperfdata_root
drwx------. 2 root root       6 May  6 18:26 systemd-private-mJ8R9P
drwx------. 2 root root       6 May  6 18:26 systemd-private-K1xEDE
drwx------. 3 root root      16 May  9 14:11 systemd-private-24f61cb6e5694eec8ceee3d1ffd01de8-rtkit-daemon.service-UbA0xq
drwx------. 3 root root      16 May  9 14:12 systemd-private-24f61cb6e5694eec8ceee3d1ffd01de8-colord.service-WQFtaR
drwx------. 3 root root      16 May  9 19:06 systemd-private-24f61cb6e5694eec8ceee3d1ffd01de8-ntpd.service-4xxWzf
-rw-r--r--. 1 root root 4803609 May  9 19:07 consul_0.5.2_linux_amd64.zip
-rw-r--r--. 1 root root 3305966 May  9 19:07 serf_0.6.4_linux_amd64.zip
-rw-r--r--. 1 root root 2192414 May 10 00:36 contiv-compose.bz2
-rw-r--r--. 1 root root 8136821 May 10 00:37 etcd-v2.3.1-linux-amd64.tar.gz
-rw-r--r--. 1 root root    2961 May 10 00:50 docker_subscription.lic

Global var settings -

[cluster-admin@Docker-1 ansible]$ clusterctl global get
{
    "extra-vars": {
        "contiv_network_mode": "standalone",
        "control_interface": "enp6s0",
        "docker_device": "/dev/sdb",
        "docker_device_size": "100000MB",
        "docker_version": "1.11.0",
        "env": {
            "HTTPS_PROXY": "http://64.102.255.40:8080",
            "HTTP_PROXY": "http://64.102.255.40:8080",
            "NO_PROXY": "",
            "http_proxy": "http://64.102.255.40:8080",
            "https_proxy": "http://64.102.255.40:8080",
            "no_proxy": ""
        },
        "fwd_mode": "bridge",
        "netplugin_if": "enp7s0",
        "scheduler_provider": "ucp-swarm",
        "service_vip": "10.65.122.79",
      *\*  "ucp_bootstrap_node_name": "Docker-2-FLM19379EUC",**
        "ucp_license_file": "/home/cluster-admin/docker_subscription.lic",
        "ucp_version": "1.1.0",
        "validate_certs": "false"
    }
}

Command used to commission the node - 

**1. clusterctl node c Docker-2-FLM19379EUC --host-group=service-master
**
**2. clusterctl node c Docker-2-FLM19379EUC --host-group=service-master -e '{"ucp_bootstrap_node_name": "Docker-2-FLM19379EUC"}'**

Both cases we have the same failure.

Complete clusterctl logs are attached herewith.

**Comment by rkharya** [comment]
[clusterm-log-0510.txt](https://github.com/contiv/ansible/files/256682/clusterm-log-0510.txt)

**Comment by rkharya** [comment]
current ansible/fetch directory is empty -

[cluster-admin@Docker-1 fetch]$ pwd
/home/cluster-admin/ansible/fetch
[cluster-admin@Docker-1 fetch]$ ls -ltr
total 0

Whereas older version of ansible/cluster-manager code base we do see fetch is populated with both ucp-fingerprint and ucp-instance-id -

[cluster-admin@contiv-aci-scale-1 ucp]$ pwd
/home/cluster-admin/ansible/fetch/ucp

[cluster-admin@contiv-aci-scale-1 ucp]$ ls -ltr
total 8
-rw-r--r-- 1 root root 78 Apr 25 23:47 ucp-fingerprint
-rw-r--r-- 1 root root 60 Apr 25 23:47 ucp-instance-id
[cluster-admin@contiv-aci-scale-1 ucp]$ file ucp-fingerprint
ucp-fingerprint: ASCII text, with CRLF line terminators
[cluster-admin@contiv-aci-scale-1 ucp]$ cat ucp-fingerprint
SHA1 Fingerprint=C8:AE:C0:09:EC:4E:8B:23:C2:31:45:ED:B1:FF:4A:7E:64:74:3B:91
[cluster-admin@contiv-aci-scale-1 ucp]$ cat ucp-instance-id
RKBR:P5GR:4NV6:DN4E:TIE5:FCCL:3TYJ:VMT3:KWLD:DAD6:VJQF:U3WU

**Comment by mapuri** [comment]
Thanks @rkharya 

I will look into this.

Can you also share the output of `journalctl -xu ucp` from `Docker-2` host?

**Comment by rkharya** [comment]
[journalctl_ucp.txt](https://github.com/contiv/ansible/files/258681/journalctl_ucp.txt)

**Comment by mapuri** [comment]
Looks like the ports that UCP used to use have changed in version 1.1, so we will need to update the defaults accordingly.

Following are the old values, you can override these in `globals` command for now to proceed.

```
ucp_port1: "12376"
ucp_port2: "12379"
ucp_port3: "12380"
ucp_port4: "12381"
ucp_port5: "12382"
```

```
May 10 00:51:28 Docker-2.cisco.com ucp.sh[24420]: INFO[0000] Checking that required ports are available and accessible
May 10 00:51:28 Docker-2.cisco.com ucp.sh[24420]: FATA[0037] The following required ports are blocked on your host: 12383, 12385, 12384, 12386.  Check your firewall settings.
```
