### ISSUE TITLE
AnsibleUndefinedVariable: 'etcd_master_name' is undefined

### ISSUE THREAD

**Issue by angry-tony** [contiv/ansible#207]
Hi. i'm new to contiv project. 
I'm going to setup contiv using ansible. but i got the ansible's error..
some advice to me.. thanks..

ran command

```
ansible-playbook --private-key=~/.ssh/id_rsa -i /tmp/hosts -e '{"env": {}, "control_interface": "eth1"}' ./site.yml
```

error

```
fatal: [contiv-volplugin-04]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'etcd_master_name' is undefined"}
```

**Comment by jainvipin** [comment]
ping @mapuri, @erikh

**Comment by angry-tony** [comment]
can i use like this??

```
 ansible]$ vim roles/etcd/defaults/main.yml
...
...
# following variables are used in one or more roles, but have no good default value to pick from.
# Leaving them as commented so that playbooks can fail early with variable not defined error.

#etcd_master_addr:
#etcd_master_name:
etcd_master_addr: "{{ hostvars[inventory_hostname]['ansible_' + control_interface]['ipv4']['address'] }}"
etcd_master_name: "{{ inventory_hostname }}"
```

**Comment by vvb** [comment]
@angry-tony `etcd_master_name` is the hostname of the server running the `etcd`. 
You need to defined a host-group "service-master" in /tmp/hosts and then, use the same hostname as `etcd_master_name`

There are a few more mandatory variables that need to be set up, they are explained at  https://github.com/contiv/cluster/blob/master/management/ansible_vars.md

recommended way of deploying a contiv cluster is to follow steps at https://github.com/contiv/cluster/tree/master/management - this uses contiv/ansible internally.

**Comment by angry-tony** [comment]
@vvb 

thanks your reply.. 
I got another error.. what is the "ansible_eth0"?? control_interface??
how to fix it?? help me...

```
[cluster-admin@node-01 ansible]$ ansible-playbook -i /tmp/hosts -e '{"env": {}, "control_interface": "eth0", "netplugin_if": "eth1", "service_vip": "172.16.0.252"}' ./site.yml
```

```
[cluster-admin@node-01 ansible]$ cat /tmp/hosts
[volplugin-test]
node-05 ansible_host=172.16.0.203
node-06 ansible_host=172.16.0.204

[service-master]
node-01 ansible_host=172.16.0.101
node-02 ansible_host=172.16.0.102

[service-worker]
node-03 ansible_host=172.16.0.201
node-04 ansible_host=172.16.0.202

[netplugin-node]
node-07 ansible_host=172.16.0.205
```

error

```
changed: [node-05] => (item=7001)

TASK [etcd : copy the etcd start/stop script] **********************************
Monday 23 May 2016  18:50:17 +0900 (0:00:01.255)       0:00:21.706 ************ 
fatal: [node-06]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'ansible_eth0'"}
fatal: [node-05]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'ansible_eth0'"}
```

**Comment by vvb** [comment]
@angry-tony this is likely because you are using the wrong interface name as `control_if`. You need to find the host interface that corresponds to the IP mentioned in `/tmp/hosts` and use that as `control_if`. That should resolve this. use `ifconfig` or `ip a` on the hosts to drill down.

**Comment by angry-tony** [comment]
@vvb 

thanks your info.

my solution is below..
I changed the site.yml file.

add 

```
- hosts: all
  tasks: []
```

refer to below

```
https://github.com/ansible/ansible/issues/9260
https://github.com/Capgemini/Apollo/pull/685/commits/e19523b3b566cf0fe24f0c8ea7c26bc70ed99551
```

**Comment by vvb** [comment]
@angry-tony that does not seem right to me. You might just need to set the correct `control_if`

**Comment by angry-tony** [comment]
@vvb I found out the hint to solve it in your vagrantfile.

ansible.limit = 'all'

```
ansible-playbook --limit all -i /tmp/hosts -e '{"env": {}, "control_interface": "eth0", "netplugin_if": "eth1", "service_vip": "172.16.0.252"}'  ./site.yml
```

it's work.. great.. :)

thank you. vvb.

**Comment by mapuri** [comment]
@angry-tony 

I am going to close this issue as looks like @vvb 's suggestion worked for you. Please feel free to reopen if that is not correct.
