### ISSUE TITLE
Deploying the playbooks will fail on CentOS 7 if docker already installed

### ISSUE THREAD

**Issue by erjosito** [contiv/ansible#21]
Running aci_demo_installer will fail if docker was previously installed in a centos7, either before running aci_demo_installer, or when running aci_demo_installer for the 2nd time.

I am running the installer as root in a CentOS7 bare metal server, got the error in the first work node, but after rerunning aci_demo_installer, I got it in the master node as well.

The workaround is uninstalling docker from all nodes (yum erase docker-engine -y) before running aci_demo_installer.

Here the error message:

TASK: [base | remove older docker and etcd] ***********************************
changed: [node2] => (item={'src': '/usr/bin/docker'})
ok: [node2] => (item={'src': '/usr/bin/etcd'})
ok: [node2] => (item={'src': '/etc/systemd/system/docker.service.d/http-proxy.conf'})
failed: [node2] => (item={'src': '/var/lib/docker'}) => {"failed": true, "item": {"src": "/var/lib/docker"}}
msg: rmtree failed: [Errno 16] Device or resource busy: '/var/lib/docker/devicemapper/mnt/84a9ed0763cdd5650bb142cfea56910f1b6c7a7b36ff0b58abfcc7531d00e60d'
FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/site.retry
node2                      : ok=13  changed=11  unreachable=0    failed=1

**Comment by mapuri** [comment]
@erjosito 

There is no task named `remove older docker and etcd` in the master and it hasn't been there. Are you trying a private fork of this repo? If so you might want to report this issue there to get a resolution. From the error it appears the docker daemon is not being stopped before deleting docker specific files.

/cc @jainvipin @jojimt in case they are interested.

**Comment by mapuri** [comment]
@DivyaVavili @erjosito , do you think this can be closed now? Is it addressed in the new netplugin installer?

**Comment by erjosito** [comment]
Sure
