### ISSUE TITLE
aci_demo_installer will fail if bzip2 is not installed in the worker nodes (Centos7)

### ISSUE THREAD

**Issue by erjosito** [contiv/ansible#22]
Workaround: install bzip2 manually in the worker nodes

TASK: [contiv_network | install netmaster and netplugin] **********************
failed: [node2] => {"changed": true, "cmd": "tar vxjf /tmp/contivnet.tar.bz2", "delta": "0:00:00.007268", "end": "2016-01-07 08:08:07.476339", "rc": 2, "start": "2016-01-07 08:08:07.469071", "warnings": ["Consider using unarchive module rather than running tar"]}
stderr: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/site.retry

node2                      : ok=43  changed=24  unreachable=0    failed=1

**Comment by mapuri** [comment]
@erjosito thanks for reporting this. Looks like we are indeed missing a task to install bzip2, I shall be able to submit a patch for this in a bit.

But similar to #21 if you are using a private fork of this repo you might want to report the issue there as well to get a resolution specific to that fork.

/cc @jainvipin @jojimt

**Comment by jainvipin** [comment]
@mapuri - we are in process of upstreaming the changes into ansible repo along the lines of @DivyaVavili's changes. I had requested @erjosito to track the issue here...

@erjosito: is it possible to provide the environment to reproduce this issue? Just docker pre-installed? and run the script? From the above it seems like download of netplugin binaries itself failed...

**Comment by mapuri** [comment]
@jainvipin ah, thanks for clarifying !

> From the above it seems like download of netplugin binaries itself failed.

The error `bzip2: Cannot exec: No such file or directory`  does appear to be bzip related as @erjosito has reported

**Comment by jainvipin** [comment]
yes it seems some more folks tried around the workaround that @erjosito had tried; knowing that workaround will certainly help nail the issue...
