### ISSUE TITLE
Question : how to integrate mantl and contiv

### ISSUE THREAD

**Issue by angry-tony** [contiv/ansible#251]
Hi.. there..

I'm new to contiv and have testing it..

I have a question...
i want to use contiv(netplugin & volplugin) to control network & storage on mantl.
how to integrate mantl and contiv (netplugin and volplugin)??
is there ansible playbooks to install them on mantl??

**Comment by mapuri** [comment]
@angry-tony 

The ansible repo is a bunch of plays that can be used for following broad use-cases at the moment:
- configure contiv-network and storage (binaries and their dependencies) along with a scheduler (swarm or ucp) and a data-store (etcd) in a clustered environment (masters and workers).
  - This is mostly suited for bringing up a cluster of nodes from almost no configuration or packages. the https://github.com/contiv/cluster repo uses the ansible for this use case.
  - the host-groups of interest are: `service-master` and `service-worker`
- configure contiv-storage along with a scheduler (swarm or ucp) and a data-store (etcd) 
  - this is used for volplugin demo and test setup
  - the host-group of interest is: `volplugin-test`
- configure contiv-network along with a scheduler (swarm or ucp) and a data-store (etcd) 
  - this is used for netplugin demo setups
  - the host-group of interest is: `netplugin-node`

There is another possibility too i.e. just directly use the roles especially `contiv-storage` and `conitv-network` but bringup rest of the stuff (scheduler, data-store etc) yourself. This hasn't been tried so there might be some tweaks needed but I don't see why wouldn't it work.

I am not very familiar with mantl, so not sure which use case will suit better. Can you explain a bit more as to where do you see this integrate with mantl?

**Comment by rhim** [comment]
Not applicable anymore.
