### ISSUE TITLE
ansible script is not installing correct docker_version

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/ansible#253]
even if we set docker_version to 1.11.1 in net_demo_installer script, Ansible scripts are not installing that docker version whenever your swarm cluster is ready.

**Comment by mapuri** [comment]
@gaurav-dalvi this is already tested in various places (like volplugin and cluster-mgr Vagrantfiles for instance). Can you please check if net_demo_installer is setting up the version in the way you want. I will try to reproduce as well.

**Comment by mapuri** [comment]
looks like demo installer is set to pick 1.10.3 for Centos (https://github.com/contiv/demo/blob/master/net/net_demo_installer#L216)

**Comment by gaurav-dalvi** [comment]
@mapuri : Thanks. I will fix it !

**Comment by mapuri** [comment]
no worries, I will close this issue then.
