### ISSUE TITLE
ansible-playbook not validating wrong control interface ID

### ISSUE THREAD

**Issue by pradvara** [contiv/ansible#258]
- Runb the ansible playbook with incorrect "control_interface".
- The anisble runs fine without throwing any error.

ansible-playbook --key-file=~/.ssh/id_rsa -i /tmp/hosts -e '{"env": {"http_proxy=http://proxy-wsa.esl.cisco.com:80","https_proxy": "http://proxy-wsa.esl.cisco.com:80"}, "validate_certs": "false", "control_interface": "enp1s"}' ./site.yml

**Comment by mapuri** [comment]
thanks @pradvara. 

Basically, we need some sort of validation checks that are run ahead of time (at least for the mandatory variables that we have). Let me see if I can work on adding something to address it this week.

We already have the issue #87 to track this, so I will close this one to avoid duplicates.
