### ISSUE TITLE
Docker role fails on task "start docker tcp socket service".. Failure reason: docker-tcp.socket fails: Socket service docker.service already active

### ISSUE THREAD

**Issue by dvavili** [contiv/ansible#26]
Docker role fails with the following message:
TASK: [docker | start docker tcp socket service] ******************************
failed: [node1] => {"failed": true}
msg: Job for docker-tcp.socket failed. See "systemctl status docker-tcp.socket" and "journalctl -xe" for details. 

contivuser@server:~$ sudo systemctl status -ln100 docker-tcp.socket
● docker-tcp.socket - Docker Socket for the API
   Loaded: loaded (/etc/systemd/system/docker-tcp.socket; disabled; vendor preset: enabled)
   Active: inactive (dead)
   Listen: [::]:2385 (Stream)

Jan 11 14:05:42 server systemd[1]: Socket service docker.service already active, refusing.
Jan 11 14:05:42 server systemd[1]: Failed to listen on Docker Socket for the API.
Jan 11 14:15:05 server systemd[1]: Socket service docker.service already active, refusing.
Jan 11 14:15:05 server systemd[1]: Failed to listen on Docker Socket for the API.

Seems to be the same issue as mentioned here: https://github.com/coreos/coreos-vagrant/issues/172
We could try to incorporate the solutions that have been suggested in the mentioned thread.

**Comment by mapuri** [comment]
@DivyaVavili 

thanks for filing the issue, can you add some more details like:
- whether docker and swarm were already installed on setup (using different steps than our ansible?)
- docker and swarm versions if they were already installed
- the error in log indicates that a service is listening on port 2385, did you happen to check what service was that (may be we can use `netstat -atp`)?

**Comment by mapuri** [comment]
actually, nm...I may be wrong... the error tells that docker is already running. So, we need to stop docker (if it's running) before installing tcp-socket service. I will try to reproduce locally.
