### ISSUE TITLE
epel-release repo is also installing ansible 2.1.1.0 now

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/ansible#264]
Reference issue : https://github.com/contiv/ansible/issues/259

epel-testing to epel-release repo transition wont work now.  ansible 2.1.1.1 version gets installed and then our ansible scripts will fail because of this error :

```
TASK [include] *****************************************************************
included: /home/admin/ansible/roles/ucarp/tasks/cleanup.yml for node1, node2
fatal: [node1]: FAILED! => {"failed": true, "reason": "'item' is undefined"}
...ignoring
fatal: [node2]: FAILED! => {"failed": true, "reason": "'item' is undefined"}
```

**Comment by gaurav-dalvi** [comment]
Current workaround. (for Centos)
1: Remove current ansible
`sudo yum remove ansible`

2: Install ansible 2.1.0

```
sudo easy_install pip
sudo pip install ansible==2.1.0.0
```

**Comment by erikh** [comment]
Just delete the repo reference in `/etc/yum/repos.d` or whatever that dir is. should be called `epel-testing.repo` so you can `find` for that to remove.

**Comment by gaurav-dalvi** [comment]
Moving this to appropriate repo contiv/demo.
Hence closing this one.

**Comment by erikh** [comment]
This an ansible problem….

/cc @mapuri

**Comment by mapuri** [comment]
@gaurav-dalvi 

mixing `pip` with `yum` can mess up package management in unknown ways ( https://github.com/contiv/ansible/issues/37), so the work-around using pip might not be a good option.

Let's keep this open to track the desired fix needed in this repo.
