### ISSUE TITLE
Service VIP interface is not getting removed after decommissioning all the nodes in ACI setup

### ISSUE THREAD

**Issue by pradvara** [contiv/ansible#265]
[stack@aci-rack1 ~]$  clusterctl nodes get | grep " status"
aci-rack1-FCH1726V18M:    status: Decommissioned
aci-rack2-FCH1752V081:    status: Decommissioned
aci-rack3-FCH1652V1R5:    status: Decommissioned
aci-rack4-FCH1849V1S5:    status: Decommissioned
aci-rack5-FCH1752V087:    status: Decommissioned

503: enp1s0f0_0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether de:0e:6f:6c:61:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.106.240.100/32 scope global enp1s0f0_0
       valid_lft forever preferred_lft forever
    inet6 fe80::dc0e:6fff:fe6c:61a6/64 scope link
       valid_lft forever preferred_lft forever

[stack@aci-rack1 ~]$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

[stack@aci-rack1 ~]$ netmaster --version
Version: v0.1-08-10-2016.10-55-19.UTC
GitCommit: f63775c
BuildTime: 08-10-2016.10-55-19.UTC

**Comment by mapuri** [comment]
@pradvara thanks for reporting this

this is related to #264 , basically with ansible 2.1.1.0 the cleanup tasks are not running correctly so the state get's leftover. I will close this and we can track the fix through #264
