### ISSUE TITLE
contivctl installation fails in contiv_network role

### ISSUE THREAD

**Issue by dvavili** [contiv/ansible#27]
With golang no longer getting installed with base role, contiv_network role fails on "install contivctl" task 

TASK: [contiv_network | install contivctl] ************************************
failed: [node1] => {"changed": true, "cmd": ". /etc/profile.d/00golang.sh && go get github.com/contiv/contivctl", "delta": "0:00:00.001944", "end": "2016-01-11 17:51:11.875943", "rc": 2, "start": "2016-01-11 17:51:11.873999", "warnings": []}
stderr: /bin/sh: 1: .: Can't open /etc/profile.d/00golang.sh

FATAL: all hosts have already failed -- aborting

Could move contivctl to an appropriate role/install necessary prerequisites for this to succeed.

**Comment by mapuri** [comment]
discussed on slack it is desirable to have github release setup for contivctl and using a released version in ansible.
