### ISSUE TITLE
Current ansible is breaking for baremetal swarm functionality

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/ansible#278]
This PR : https://github.com/contiv/ansible/pull/275 broke current swarm installation functionality.
service_vip is not getting value and netmaster is not coming up properly.

**Comment by gaurav-dalvi** [comment]
@erikh : Could you please take a look at this one ?

**Comment by erikh** [comment]
yes

**Comment by gaurav-dalvi** [comment]
Closing. It was fixed because of fixing ansible 2.2.0 and not using previous versions.
