### ISSUE TITLE
Install golang using ansible on nodes.

### ISSUE THREAD

**Issue by unclejack** [contiv/ansible#295]
The GOPATH and the environment need to be set up as well. This should also be available for installation outside of the dev role.

**Comment by gaurav-dalvi** [comment]
1: Install golang on only master node. (version of golang should be configurable)
2: set following environment variables:

export PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/admin
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

**Comment by gaurav-dalvi** [comment]
Dup of https://github.com/contiv/ansible/issues/293

**Comment by rhim** [comment]
Folks, just to clarify, is this issue closed by PR #293 ? If so, please mark it closed.

**Comment by unclejack** [comment]
This issue is no longer relevant. The required roles are already in the playbooks. The installation of Go and other tools falls in another area. The tools which use these playbooks should use the existing role.
