### ISSUE TITLE
Update docker role to incorporate new changes for docker 1.12

### ISSUE THREAD

**Issue by dvavili** [contiv/ansible#301]
With docker 1.12, docker.service removes the requires of requiring docker.socket. Update ansible scripts to handle this.

**Comment by dvavili** [comment]
References:
https://github.com/docker/docker/issues/25559
https://github.com/docker/docker/pull/25094

**Comment by unclejack** [comment]
This is easy to fix to make it work with Docker 1.12. The Docker role needs to maintain compatibility with Docker 1.11.

I'll asign this to myself. I've run into this issue when I was trying to bump the Docker version to 1.12 in ansbile a few days ago.
