### ISSUE TITLE
error while executing net_demo_installer 

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/ansible#308]
TASK [cleanup iptables for etcd] ***********************************************
[WARNING]: The loop variable 'item' is already in use. You should set the loop_var value in the loop_control option for the task to something else to avoid variable collisions and unexpected behavior.

failed: [node1] (item=2379) => {"changed": true, "cmd": "iptables -D INPUT -p tcp --dport 2379 -j ACCEPT -m comment --comment "etcd traffic (2379)"", "delta": "0:00:00.004369", "end": "2017-01-19 19:38:45.554219", "failed": true, "item": 2379, "rc": 1, "start": "2017-01-19 19:38:45.549850", "stderr": "iptables: Bad rule (does a matching rule exist in that chain?).", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [node1] (item=4001) => {"changed": true, "cmd": "iptables -D INPUT -p tcp --dport 4001 -j ACCEPT -m comment --comment "etcd traffic (4001)"", "delta": "0:00:00.004352", "end": "2017-01-19 19:38:45.771600", "failed": true, "item": 4001, "rc": 1, "start": "2017-01-19 19:38:45.767248", "stderr": "iptables: Bad rule (does a matching rule exist in that chain?).", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [node1] (item=2380) => {"changed": true, "cmd": "iptables -D INPUT -p tcp --dport 2380 -j ACCEPT -m comment --comment "etcd traffic (2380)"", "delta": "0:00:00.004353", "end": "2017-01-19 19:38:45.987596", "failed": true, "item": 2380, "rc": 1, "start": "2017-01-19 19:38:45.983243", "stderr": "iptables: Bad rule (does a matching rule exist in that chain?).", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
failed: [node1] (item=7001) => {"changed": true, "cmd": "iptables -D INPUT -p tcp --dport 7001 -j ACCEPT -m comment --comment "etcd traffic (7001)"", "delta": "0:00:00.004506", "end": "2017-01-19 19:38:46.203960", "failed": true, "item": 7001, "rc": 1, "start": "2017-01-19 19:38:46.199454", "stderr": "iptables: Bad rule (does a matching rule exist in that chain?).", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [stop nfs services (redhat)] **********************************************
[WARNING]: The loop variable 'item' is already in use. You should set the loop_var value in the loop_control option for the task to something else to avoid variable collisions and unexpected behavior.

failed: [node1] (item=rpcbind) => {"failed": true, "item": "rpcbind", "msg": "Could not find the requested service rpcbind: cannot check nor set state"}
failed: [node1] (item=nfs-server) => {"failed": true, "item": "nfs-server", "msg": "Could not find the requested service nfs-server: cannot check nor set state"}
failed: [node1] (item=rpc-statd) => {"failed": true, "item": "rpc-statd", "msg": "Could not find the requested service rpc-statd: cannot check nor set state"}
...ignoring
failed: [node1] (item=nfs-idmapd) => {"failed": true, "item": "nfs-idmapd", "msg": "Could not find the requested service nfs-idmapd: cannot check nor set state"}

TASK [stop nfs services (debian)] **********************************************
[WARNING]: The loop variable 'item' is already in use. You should set the loop_var value in the loop_control option for the task to something else to avoid variable collisions and unexpected behavior.

failed: [node1] (item=nfs-kernel-server) => {"failed": true, "item": "nfs-kernel-server", "msg": "Could not find the requested service nfs-kernel-server: cannot check nor set state"}
...ignoring
failed: [node1] (item=nfs-common) => {"failed": true, "item": "nfs-common", "msg": "Could not find the requested service nfs-common: cannot check nor set state"}

TASK [stop docker] *************************************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service docker: cannot check nor set state"}
...ignoring

TASK [stop docker tcp socket] **************************************************
ok: [node1]

TASK [cleanup iptables for docker] *********************************************
[WARNING]: The loop variable 'item' is already in use. You should set the loop_var value in the loop_control option for the task to something else to avoid variable collisions and unexpected behavior.

...ignoring
failed: [node1] (item=2385) => {"changed": true, "cmd": "iptables -D INPUT -p tcp --dport 2385 -j ACCEPT -m comment --comment "docker api (2385)"", "delta": "0:00:00.004346", "end": "2017-01-19 19:38:48.327426", "failed": true, "item": 2385, "rc": 1, "start": "2017-01-19 19:38:48.323080", "stderr": "iptables: Bad rule (does a matching rule exist in that chain?).", "stdout": "", "stdout_lines": [], "warnings": []}
to retry, use: --limit @/root/ansible/cleanup.retry

PLAY RECAP *********************************************************************
node1 : ok=42 changed=11 unreachable=0 failed=0
node2 : ok=0 changed=0 unreachable=1 failed=0

[root@pod25-srv1 ~]#

ansible --version
ansible 2.2.1.0
config file = /root/.ansible.cfg
configured module search path = Default w/o overrides
[root@pod25-srv1 ~]#

**Comment by neelimamukiri** [comment]
@gaurav-dalvi, we discussed this yesterday. The issue here is the node2 not being reachable.
PLAY RECAP *********************************************************************
node1 : ok=42 changed=11 unreachable=0 failed=0
node2 : ok=0 changed=0 unreachable=1 failed=0

**Comment by dvavili** [comment]
@gaurav-dalvi: As @neelimamukiri has mentioned, this is not an issue with installer. Once the FQDN was provided, the installer proceeded to finish the tasks. The warning you are seeing does not affect the functionality here.

**Comment by gaurav-dalvi** [comment]
not seeing this issue anymore.
