### ISSUE TITLE
AWS tf script, display output

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/ansible#318]
Once scripts executes successfully, Please provide following details. Preferably in this format
machine1:IP,eth0:IP,eth1:IP
machine2:IP,eth0:IP,eth1:IP
machine3:IP,eth0:IP,eth1:IP ...

**Comment by gaurav-dalvi** [comment]
feel free to create your own formate. Formate is not important content is important.

**Comment by dojacobs** [comment]
Added output statement to aws.tf script which outputs list of private IP#s:
54.172.35.5,
54.133.23.6,
54.23.18.1

(aws.tf script change has been merged into contiv/ansible)

E2E Pipeline script on Jenkins takes this list, and turns it into a string:
"54.172.35.5 54.133.23.6 54.23.18.1"

This way it can be inserted on the command line for the script to generate the cfg.yml file used by the Installer.
