### ISSUE TITLE
ERROR! environment must be a dictionary, received env

### ISSUE THREAD

**Issue by dgouju** [contiv/ansible#32]
At the beginning of Ansible playbook run on master node:
TASK [base : ensure custom facts directory exists] *****************************
[DEPRECATION WARNING]: Using bare variables for environment is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{foo}}'). This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
fatal: [node1]: FAILED! => {"failed": true, "msg": "ERROR! environment must be a dictionary, received env (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}

PLAY RECAP *********************************************************************
node1                      : ok=1    changed=0    unreachable=0    failed=1

—> To correct, you have to change in ./ansible/site.yml all the « environment: env »  to « environment: '{{env}}’ » according to https://github.com/ansible/ansible/issues/11912

Here is a proposed patch. 
[site.txt](https://github.com/contiv/ansible/files/90013/site.txt)

**Comment by jainvipin** [comment]
@dgouju - can you also tell the ansible version you are running? It will help the recreation and verification of this issue.

**Comment by dgouju** [comment]
It is 2.0.0.1

**Comment by jainvipin** [comment]
awesome, thanks @dgouju !
