### ISSUE TITLE
systemd could not find the requested service etcd

### ISSUE THREAD

**Issue by dgouju** [contiv/ansible#33]
After Docker and etcd installation, we got the following error:
TASK [base : stop etcd] ********************************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'etcd'\": « }

And we found that there is no service file in /etc/systemd/ or /lib/systemd .

Here is a proposed patch.
[main.txt](https://github.com/contiv/ansible/files/90014/main.txt)

**Comment by jainvipin** [comment]
thanks @dgouju !
We'll incorporate the fix... once the changes you tried our are merged in. If they were part of this repo, you could have submitted the PR itself.

**Comment by mapuri** [comment]
I think PR would not work (pass sanity) in this case as there is no task called `stop etcd` in the `base` role. We can leave this issue open until @DivyaVavili changes are posted as a PR.

**Comment by mapuri** [comment]
@DivyaVavili @dgouju , do you think this can be closed now? Is it addressed in the new netplugin installer?

**Comment by dvavili** [comment]
@mapuri : Lets wait until it's tested with the cleanup tasks after all the ansible changes for the installer is in. Will update the status after that.

**Comment by mapuri** [comment]
@DivyaVavili sounds good, thanks.

**Comment by dvavili** [comment]
@mapuri : Checked it with the latest ansible changes with additional etcd cleanup changes and don't see this issue after running cleanup.yml. Please feel free to close this.

**Comment by mapuri** [comment]
@DivyaVavili thanks for confirming. Closing this.
