### ISSUE TITLE
Local State of Contiv Ansible Thinks etcd running

### ISSUE THREAD

**Issue by acusworth** [contiv/ansible#47]
After rebooting a cluster of Contiv VMs the netmaster and etcd services wouldn't come back up.
Reboot occurred after increasing the VM's number of cores from 1 to 2 and increasing the memory from 1G to 8G.
Attempted to restart contiv with the "startPlugin.py" script and after attempted to reinstall the whole package with "net_demo_installer". After running script checked status of the etcd and netmaster services both reported failing. Manually starting etcd service on both the primary and secondary node failed.

Citing code segment. This code is from /usr/bin/etcd.sh shell script that is called by ansible installer to restart:

if [ ! -f /var/tmp/etcd.existing ]; then
        touch /var/tmp/etcd.existing
        export ETCD_INITIAL_CLUSTER_STATE=new
        export ETCD_INITIAL_CLUSTER="node1=http://10.88.38.75:2380,node1=http://10.88.38.75:7001,node2=http://10.88.38.73:2380,node2=http://10.88.38.73:7001"
    else
                                    # XXX: There seems an issue using etcdctl with ETCD_INITIAL_ADVERTISE_PEER_URLS so passing
    # ETCD_LISTEN_PEER_URLS for now
    out=`etcdctl --peers="10.88.38.73:2379,10.88.38.73:4001" \
        member add node1 "$ETCD_LISTEN_PEER_U

**Comment by mapuri** [comment]
@acusworth 

Thanks for reporting the issue. Can you please share the output of following commands from the VMs?

```
sudo systemctl status -ln100 etcd
```

Also as a recovery step can you try the following (on all nodes):
- sudo systemctl stop etcd
- rm -rf /var/tmp/etcd.existing

And the then start etcd on all nodes (once above steps are done everywhere):
- sudo systemctl start etcd

I am speculating that `/var/tmp/etcd.existing` is probably getting persisted across reloads resulting in etcd script to take the wrong path.

**Comment by jainvipin** [comment]
@mapuri:

```
contiv@ContivA1:~$ service etcd status
● etcd.service - Etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2016-01-25 15:35:06 PST; 40s ago
 Main PID: 10528 (code=exited, status=1/FAILURE)

Jan 25 15:35:06 ContivA1 systemd[1]: Started Etcd.
Jan 25 15:35:06 ContivA1 systemd[1]: Starting Etcd...
Jan 25 15:35:06 ContivA1 etcd.sh[10528]: dial tcp 10.88.38.73:4001: connection refused
Jan 25 15:35:06 ContivA1 etcd.sh[10528]: failed to add member node1
Jan 25 15:35:06 ContivA1 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jan 25 15:35:06 ContivA1 etcd.sh[10539]: dial tcp 127.0.0.1:2379: connection refused
Jan 25 15:35:06 ContivA1 systemd[1]: Unit etcd.service entered failed state.
Jan 25 15:35:06 ContivA1 systemd[1]: etcd.service failed.
```

`sudo systemctl restart etcd` doesn't work, but removing the /var/tmp/etcd.existing file worked followed by a restart. Indeed @mapuri persistence of /var/tmp/etcd.existing is the issue from the etcd.sh script.

Recovering using the above operations worked fine. However with this code I am guessing that reboot of a node wouldn't work, if you try this on one single VM with a reboot. @acusworth had to do this because we asked him to resize his VM.

**Comment by mapuri** [comment]
@jainvipin 

great thanks for confirming. We can perhaps create the  `/var/tmp/etcd.existing` file in tmpfs as part of fix for this condition.

> However with this code I am guessing that reboot of a node wouldn't work, if you try this on one single VM with a reboot

Yeah, that is correct. We generate this script in ansible. So it is indeed static and will not work for more complex scenario like single node reboots. For that we will need a higher level cluster management that could handle node health changes more dynamically.

**Comment by jainvipin** [comment]
> great thanks for confirming. We can perhaps create the /var/tmp/etcd.existing file in tmpfs as part of fix for this condition.

Agree. something that doesn't persist reboots at least.

Would you know, if etcd were to fail for some reason (say it crashed, etc.), then it should ideally get restarted (by systemctl), but would that restart fail because of the same issue?

**Comment by mapuri** [comment]
> if etcd were to fail for some reason (say it crashed, etc.), then it should ideally get restarted (by systemctl),

no, systemctl won't automatically restart etcd as we don't set Restart policy for it today.

> would that restart fail because of the same issue? 

But if etcd is manually started/restarted without the node reload then it should work. I think we exercise this in volplugin tests.
