### ISSUE TITLE
New versions of binaries not downloaded and replaced

### ISSUE THREAD

**Issue by dvavili** [contiv/ansible#55]
This issue is seen for tasks where we download binary releases and install them on the server nodes.

Example scenario: 
Netplugin/netmaster binaries are downloaded from released version and installed on server-nodes
If we were to re-run the ansible playbook after running cleanup.yml playbook and then site.yml with a new release version, the new version is not downloaded and installed

Workaround:
Remove /tmp/contivnet.tar.bz2
Remove associated binaries from /usr/bin/{netplugin/netmast/netctl/contivk8s}
Rerun ansible-playbook site.yml

This issue would be seen for any such binaries/released version.

**Comment by jojimt** [comment]
This is basically a show stopper for people trying to demo. What is our plan to fix this?
In addition to fixing this, we also need a way to specify the release version for an install/restart.

**Comment by jainvipin** [comment]
Yes, saw this myself... nothing gets overwritten. Basically upgrade is completely busted.
ping @erikh - what is the typical recommendation to help with upgrades in ansible.

**Comment by dvavili** [comment]
One of the ways that I've been getting around these kind of issues is to skip some of the optimizations that are in place when binaries/service files are copied. 

For eg: 
For copying the binaries, the common approach we take is to use the shell module and unzip it to the proper location. An optimization here is to use the "creates" clause which skips the task if the file is already present. But in the case of a new binary, this is supposed to be overwritten. This is the case with many file/binary writes that we have now.

To open it up for discussion, a couple of ways this could be handled is:
1. Remove these optimizations. This could mean that the provisioning will take a little longer than usual. 
2. Add a check to see if the files differ (probably by cksum) and overwrite them. This would mean that we are introducing a lot of checks.

But are we going to use provisioning every now and then? The use cases that we have seen is that it's generally used when we are setting up or upgrading our services. If this is the case always, we could go with the first approach and skip the optimizations. Let me know your thoughts.

**Comment by jojimt** [comment]
Yes, you should be able to take in an env variable and change the behavior based on that.

**Comment by erikh** [comment]
most CM resources for downloading have an md5/sha you can compare to. we can do that and download/update as necessary with variables and notifications by passing the state on to the next steps appropriately to upgrade/install the tools.

http://docs.ansible.com/ansible/get_url_module.html will explain how to do it, under `sha256sum`.

**Comment by erikh** [comment]
sorry; `checksum` is the new school in ansible, not `sha256sum`.

**Comment by mapuri** [comment]
I think the upgrade issue is related to the following causes:
- the downloaded file names for contiv-network (and other binaries) is not tied to a version. If we embed the version in the downloaded file name then upgrades shall work fine.
- The extraction shell script usually checks for file to exist, I think we can replace that with a conditional that checks whether a new tar file was downloaded

I can work on a change to address this and will share it in a bit so my thought above will be a little more clear.
